services:
  web:
    build: . 
    ports:
      - "8000:8000"      
    volumes:
      - ../portfolio/:/code
    environment:
      DJANGO_SUPERUSER_USERNAME: alberto
      DJANGO_SUPERUSER_PASSWORD: 1234
      DJANGO_SUPERUSER_EMAIL: admin@example.com
  bd:
    image: postgres:latest
    container_name: bd-postgres
    environment:
      POSTGRES_DB: 'proyecto_django'
      POSTGRES_USER: 'alberto'
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5432:5432"